// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"bubu_admin/internal/handler"
	"bubu_admin/internal/repository"
	"bubu_admin/internal/server"
	"bubu_admin/internal/service"
	"bubu_admin/pkg/app"
	"bubu_admin/pkg/jwt"
	"bubu_admin/pkg/log"
	"bubu_admin/pkg/server/http"
	"bubu_admin/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT, viperViper)
	userRepository := repository.NewUserRepository(repositoryRepository)
	menuRepository := repository.NewMenuRepository(repositoryRepository)
	roleRepository := repository.NewRoleRepository(repositoryRepository)
	userRoleRepository := repository.NewUserRoleRepository(repositoryRepository)
	roleMenuRepository := repository.NewRoleMenuRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository, menuRepository, roleRepository, userRoleRepository, roleMenuRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	menuService := service.NewMenuService(serviceService, menuRepository)
	menuHandler := handler.NewMenuHandler(handlerHandler, menuService)
	roleService := service.NewRoleService(serviceService, roleRepository, menuRepository, roleMenuRepository)
	roleHandler := handler.NewRoleHandler(handlerHandler, roleService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler, menuHandler, roleHandler)
	job := server.NewJob(logger)
	appApp := newApp(httpServer, job)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewMenuRepository, repository.NewRoleRepository, repository.NewRoleMenuRepository, repository.NewUserRoleRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewMenuService, service.NewRoleService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewMenuHandler, handler.NewRoleHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob)

// build App
func newApp(
	httpServer *http.Server,
	job *server.Job,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, job), app.WithName("demo-server"))
}
